#!/usr/bin/env python3
"""Planner Agent — Generated by ABI-Core"""

import json

from planner import AbiPlannerAgent
from abi_core.agent import AbiCore
from abi_core.common.utils import abi_logging
from abi_core.common.semantic_tools import tool_find_agent, tool_recommend_agents

agent = AbiCore()


@agent.task(
    name="analyze_query",
    input_map={
        "query": "$input.query",
        "context": "$input.context",
    },
)
async def analyze_query(query, context):
    """Send query + context to the LLM for decomposition.

    The LLM returns JSON with either:
    - {"status": "needs_clarification", "questions": [...]}
    - {"status": "ready", "plan": {...}}

    This task only calls the LLM — parsing happens in the next step.
    """
    planning_query = f"User request: {query}\nContext: {json.dumps(context, indent=2)}"
    # Return raw query for the planner's LLM — actual LLM call happens
    # in planner.stream() which has access to self.agent
    return {"planning_query": planning_query}


@agent.task(
    name="parse_plan",
    depends_on=["analyze_query"],
    input_map={"raw_response": "$input.llm_response"},
)
def parse_plan(raw_response):
    """Clean and parse the LLM response into structured plan data."""
    if not raw_response:
        return {"status": "error", "message": "Empty LLM response"}

    cleaned = raw_response.strip()

    # Strip markdown code fences
    if cleaned.startswith('```json'):
        cleaned = cleaned[7:]
    if cleaned.startswith('```'):
        cleaned = cleaned[3:]
    if cleaned.endswith('```'):
        cleaned = cleaned[:-3]
    cleaned = cleaned.strip()

    # Fix double braces from LLM hallucination
    cleaned = cleaned.replace('{{', '{').replace('}}', '}')

    abi_logging("[🔍] Cleaned LLM response for parsing")

    try:
        plan_data = json.loads(cleaned)
    except json.JSONDecodeError as e:
        abi_logging(f"[❌] JSON parse error: {e}")
        return {
            "status": "ready",
            "plan": {
                "objective": "Complete user request",
                "tasks": [{
                    "task_id": "task_1",
                    "description": raw_response,
                    "agents": [],
                    "agent_count": 1,
                    "dependencies": [],
                }],
                "execution_strategy": "sequential",
            },
        }

    return plan_data


@agent.task(
    name="assign_agents",
    depends_on=["parse_plan"],
    input_map={"plan_data": "$parse_plan"},
)
async def assign_agents(plan_data):
    """Find and assign agents to each task in the plan.

    Skipped if the plan needs clarification or errored.
    """
    if plan_data.get("status") != "ready":
        return plan_data  # pass through clarification / error

    plan = plan_data.get("plan", {})
    tasks = plan.get("tasks", [])

    abi_logging(f"[🔍] Assigning agents to {len(tasks)} tasks...")

    for task in tasks:
        task_desc = task.get("description", "")
        agent_count = task.get("agent_count", 1)

        if agent_count == 1:
            found = await tool_find_agent.ainvoke(task_desc)
            if not found:
                recs = await tool_recommend_agents.ainvoke({
                    "task_description": task_desc,
                    "max_agents": 1,
                })
                agent_data = recs[0] if recs else None
            else:
                agent_data = found.dict() if hasattr(found, "dict") else found
            task["agents"] = [agent_data] if agent_data else []
        else:
            recs = await tool_recommend_agents.ainvoke({
                "task_description": task_desc,
                "max_agents": agent_count,
            })
            task["agents"] = recs if recs else []

        abi_logging(f"[✅] Task '{task.get('task_id')}': {len(task['agents'])} agent(s)")

    return plan_data


agent.run(AbiPlannerAgent())
