#!/usr/bin/env python3
"""
testproject - Main Application
test project

Domain: general
Generated by ABI-Core CLI
"""

import os
import json
import logging
import asyncio
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional

import uvicorn
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from config.config import config
from abi_core.common.utils import abi_logging

# Configure logging
logging.basicConfig(
    level=getattr(logging, config.log_level),
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Lifespan context manager (replaces deprecated on_event)
from contextlib import asynccontextmanager

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan - startup and shutdown"""
    
    # Startup
    logger.info(f"🚀 Starting testproject")
    logger.info(f"📋 Description: test project")
    logger.info(f"🏷️ Domain: general")
    logger.info(f"⚙️ Configuration: {config.to_dict()}")
    
    
    # Test semantic layer connection
    try:
        agents = await semantic_client.list_agents()
        logger.info(f"✅ Semantic layer connected - {len(agents)} agents registered")
    except Exception as e:
        logger.warning(f"⚠️ Semantic layer connection failed: {e}")
    
    
    
    # Test guardian connection
    try:
        import httpx
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"http://{config.guardian_host}:{config.guardian_port}/health",
                timeout=5.0
            )
            if response.status_code == 200:
                logger.info("✅ Guardian security service connected")
            else:
                logger.warning(f"⚠️ Guardian service returned {response.status_code}")
    except Exception as e:
        logger.warning(f"⚠️ Guardian connection failed: {e}")
    
    
    yield  # Application runs here
    
    # Shutdown
    logger.info("🛑 Shutting down testproject")

# FastAPI app with lifespan
app = FastAPI(
    title="testproject",
    description="test project",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Pydantic models
class AgentRequest(BaseModel):
    query: str
    context: Optional[Dict[str, Any]] = None

class AgentResponse(BaseModel):
    agent_id: Optional[str]
    agent_name: Optional[str]
    response: str
    metadata: Dict[str, Any]


class SemanticLayerClient:
    """Client for semantic layer service using MCP protocol"""
    
    def __init__(self):
        # Extract hostname from URL if it contains protocol
        if config.semantic_layer_host.startswith('http://') or config.semantic_layer_host.startswith('https://'):
            from urllib.parse import urlparse
            parsed = urlparse(config.semantic_layer_host)
            self.host = parsed.hostname
            self.port = parsed.port or config.semantic_layer_port
        else:
            self.host = config.semantic_layer_host
            self.port = config.semantic_layer_port
        self.transport = 'sse'
        
    async def find_agent(self, query: str) -> Optional[Dict[str, Any]]:
        """Find best agent for query using MCP client"""
        from abi_core.abi_mcp import client
        from abi_core.security.agent_auth import with_agent_context
        
        try:
            # Build context for system authentication (no agent card needed)
            ctx = with_agent_context(
                agent_id="system-web-api",
                tool_name="find_agent",
                mcp_method="callTool",
                user_email="system@testproject",
                query=query
            )
            
            async with client.init_session(self.host, self.port, self.transport) as session:
                result = await client.find_agent(session, query, ctx)
                
                if result.isError:
                    logger.error(f"MCP error: {result.content}")
                    return None
                
                # Parse the result content
                if hasattr(result.content, 'text'):
                    import json
                    agent_data = json.loads(result.content.text)
                    return agent_data
                elif isinstance(result.content, list) and len(result.content) > 0:
                    # Handle list response
                    content_item = result.content[0]
                    if hasattr(content_item, 'text'):
                        import json
                        agent_data = json.loads(content_item.text)
                        return agent_data
                
                return None
                    
        except Exception as e:
            logger.error(f"Error contacting semantic layer via MCP: {e}")
            return None
    
    async def list_agents(self) -> List[Dict[str, Any]]:
        """List all registered agents using MCP resource"""
        from abi_core.abi_mcp import client
        from abi_core.security.agent_auth import with_agent_context
        
        try:
            # Build context for system authentication (no agent card needed)
            ctx = with_agent_context(
                agent_id="system-web-api",
                tool_name="list_agents",
                mcp_method="readResource",
                user_email="system@testproject",
                query="list all agents"
            )
            
            async with client.init_session(self.host, self.port, self.transport) as session:
                # Use the resource endpoint to list all agents
                resource_uri = "resource://agent_cards/list/all"
                result = await client.find_resource(session, resource_uri)
                
                if hasattr(result, 'contents') and result.contents:
                    # Parse the resource content
                    content = result.contents[0]
                    if hasattr(content, 'text'):
                        import json
                        data = json.loads(content.text)
                        if data:
                            return data.get("agent_cards", [])
                
                return []
                    
        except Exception as e:
            logger.error(f"Error listing agents via MCP: {e}")
            return []

# Initialize semantic layer client
semantic_client = SemanticLayerClient()



class GuardianClient:
    """Client for guardian security service"""
    
    def __init__(self):
        # guardian_host puede incluir http://, verificar para no duplicar
        if hasattr(config, 'guardian_url') and config.guardian_url:
            self.base_url = config.guardian_url
        else:
            if config.guardian_host.startswith('http://') or config.guardian_host.startswith('https://'):
                self.base_url = config.guardian_host
            else:
                self.base_url = f"http://{config.guardian_host}:{config.guardian_port}"
        
    async def validate_access(self, agent_id: str, agent_card: Dict[str, Any], 
                            request_metadata: Dict[str, Any] = None) -> Dict[str, Any]:
        """Validate agent access via Guardian"""
        import httpx
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{self.base_url}/v1/tools/validate_semantic_access",
                    json={
                        "agent_id": agent_id,
                        "agent_card": agent_card,
                        "request_metadata": request_metadata or {}
                    },
                    timeout=10.0
                )
                
                if response.status_code == 200:
                    return response.json()
                else:
                    logger.error(f"Guardian error: {response.status_code}")
                    return {
                        "allowed": False,
                        "reason": f"Guardian service error: {response.status_code}",
                        "risk_score": 1.0
                    }
                    
        except Exception as e:
            logger.error(f"Error contacting Guardian: {e}")
            return {
                "allowed": False,
                "reason": f"Guardian service unavailable: {str(e)}",
                "risk_score": 1.0
            }

# Initialize guardian client
guardian_client = GuardianClient()


# Routes
@app.get("/")
async def root():
    """Root endpoint with service information"""
    return {
        "service": "testproject",
        "description": "test project",
        "domain": "general",
        "version": "1.0.0",
        "status": "running",
        "timestamp": datetime.utcnow().isoformat(),
        "config": {
            "abi_role": config.abi_role,
            "abi_node": config.abi_node,
            "model_name": config.model_name,
            
            "semantic_layer": f"{config.semantic_layer_host}:{config.semantic_layer_port}",
            
            
            "guardian_security": f"{config.guardian_host}:{config.guardian_port}",
            
        }
    }

@app.get("/health")
async def health():
    """Health check endpoint"""
    health_status = {
        "status": "healthy",
        "service": "testproject",
        "timestamp": datetime.utcnow().isoformat(),
        "checks": {}
    }
    
    
    # Check semantic layer
    try:
        agents = await semantic_client.list_agents()
        health_status["checks"]["semantic_layer"] = {
            "status": "healthy",
            "registered_agents": len(agents)
        }
    except Exception as e:
        health_status["checks"]["semantic_layer"] = {
            "status": "unhealthy",
            "error": str(e)
        }
        health_status["status"] = "degraded"
    
    
    
    # Check guardian
    try:
        import httpx
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"http://{config.guardian_host}:{config.guardian_port}/v1/tools/get_guardian_status",
                timeout=5.0
            )
            if response.status_code == 200:
                health_status["checks"]["guardian"] = {
                    "status": "healthy",
                    "details": response.json()
                }
            else:
                health_status["checks"]["guardian"] = {
                    "status": "unhealthy",
                    "error": f"HTTP {response.status_code}"
                }
                health_status["status"] = "degraded"
    except Exception as e:
        health_status["checks"]["guardian"] = {
            "status": "unhealthy",
            "error": str(e)
        }
        health_status["status"] = "degraded"
    
    
    return health_status

@app.get("/v1/config")
async def get_config():
    """Get current configuration"""
    return config.to_dict()


@app.get("/v1/agents")
async def list_agents():
    """List all registered agents"""
    try:
        agents = await semantic_client.list_agents()
        return {
            "agents": agents,
            "total": len(agents),
            "timestamp": datetime.utcnow().isoformat()
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error listing agents: {str(e)}")

@app.post("/v1/agents/find", response_model=AgentResponse)
async def find_agent(request: AgentRequest):
    """Find the best agent for a given query"""
    try:
        # Find agent via semantic layer
        agent_card = await semantic_client.find_agent(request.query)
        
        if not agent_card:
            return AgentResponse(
                agent_id=None,
                agent_name=None,
                response=f"No suitable agent found for query: {request.query}",
                metadata={
                    "query": request.query,
                    "found": False,
                    "timestamp": datetime.utcnow().isoformat()
                }
            )
        
        
        # Validate access via Guardian
        validation_result = await guardian_client.validate_access(
            agent_id=agent_card.get("id", "unknown"),
            agent_card=agent_card,
            request_metadata={
                "query": request.query,
                "method": "find_agent",
                "source_ip": "internal",
                "user_agent": "testproject"
            }
        )
        
        if not validation_result.get("allowed", False):
            return AgentResponse(
                agent_id=agent_card.get("id"),
                agent_name=agent_card.get("name"),
                response=f"Access denied by Guardian: {validation_result.get('reason', 'Unknown reason')}",
                metadata={
                    "query": request.query,
                    "found": True,
                    "access_denied": True,
                    "risk_score": validation_result.get("risk_score", 1.0),
                    "guardian_validation": validation_result,
                    "timestamp": datetime.utcnow().isoformat()
                }
            )
        
        
        return AgentResponse(
            agent_id=agent_card.get("id"),
            agent_name=agent_card.get("name"),
            response=f"Found agent: {agent_card.get('name')} - {agent_card.get('description')}",
            metadata={
                "query": request.query,
                "found": True,
                "agent_card": agent_card,
                
                "guardian_validation": validation_result,
                
                "timestamp": datetime.utcnow().isoformat()
            }
        )
        
    except Exception as e:
        logger.error(f"Error in find_agent: {e}")
        raise HTTPException(status_code=500, detail=f"Error finding agent: {str(e)}")





@app.get("/v1/security/status")
async def get_security_status():
    """Get security status from Guardian"""
    try:
        import httpx
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"http://{config.guardian_host}:{config.guardian_port}/v1/tools/get_security_metrics",
                timeout=10.0
            )
            
            if response.status_code == 200:
                return response.json()
            else:
                raise HTTPException(status_code=response.status_code, detail="Guardian service error")
                
    except Exception as e:
        logger.error(f"Error getting security status: {e}")
        raise HTTPException(status_code=500, detail=f"Error getting security status: {str(e)}")

@app.post("/v1/security/block_agent")
async def block_agent(request: dict):
    """Block an agent via Guardian"""
    try:
        agent_id = request.get("agent_id", "")
        reason = request.get("reason", "Manual block via API")
        
        if not agent_id:
            raise HTTPException(status_code=400, detail="agent_id is required")
        
        import httpx
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"http://{config.guardian_host}:{config.guardian_port}/v1/tools/block_agent",
                json={"agent_id": agent_id, "reason": reason},
                timeout=10.0
            )
            
            if response.status_code == 200:
                return response.json()
            else:
                raise HTTPException(status_code=response.status_code, detail="Guardian service error")
                
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error blocking agent: {e}")
        raise HTTPException(status_code=500, detail=f"Error blocking agent: {str(e)}")


def main():
    """Main entry point"""
    logger.info(f"🌟 testproject starting on {config.agent_host}:{config.agent_port}")
    
    uvicorn.run(
        "main:app",
        host=config.agent_host,
        port=config.agent_port,
        reload=config.debug,
        log_level=config.log_level.lower()
    )

if __name__ == "__main__":
    main()