#!/usr/bin/env python3
"""Orchestrator Agent — Generated by ABI-Core"""

from orchestrator import AbiOrchestratorAgent
from web_interface import OrchestratorWebinterface
from abi_core.agent import AbiCore

app = AbiCore(
    web_interface_cls=OrchestratorWebinterface,
    interface_name="Orchestrator Web Interface",
)
app.run(AbiOrchestratorAgent())
